language: csharp
solution: FragmentNetslumServer.sln
mono: none
dotnet: 6.0.100
script:
  - dotnet restore
  - dotnet build -c Release
  - sonar-scanner
addons:
  sonarcloud:
    organization: "zackmon" # the key of the org you chose at step #3
      
  
