language: csharp
solution: FragmentServerWV.sln
mono: none
dotnet: 3.1.11
script:
  - dotnet restore
  - dotnet build -c Release
  - sonar-scanner
addons:
  sonarcloud:
    organization: "zackmon" # the key of the org you chose at step #3
      
  